### ISSUE TITLE
TODO before first public version

### ISSUE THREAD

**Issue by Alan-FGR** [Alan-FGR/aelum#1]
- [ ] remove vec2f class
- [ ] rename components to plugin so people don't think it's real ECS
- [ ] get rid of mainCam static
- [ ] implement proper zpos for quads/sprites using entity ypos and origin (+opt offset?)
- [ ] light system serialization
- [ ] sprite component serialization (low priority, we use quads for most stuff)
- [ ] revamp rendering - getting rts from cams and manually rendering to fb sucks
- [ ] add optional randomization for 'shaking' lights (e.g. bonfires)
- [ ] spatially optimized sound system
- [ ] efficient sounds pool for oneshots
- [ ] fix quads shear effect - should be aligned
- [ ] use float for pixel size to allow zooming out from 1:1
- [ ] finish optional 1D and 2D origin shifting
- [ ] use entities AABBs not just origin for culling
- [ ] allow multiple textures - so sprites hold texture not just UV rectf
- [ ] fix UI layouts always updating no matter what - dirtying?
- [ ] implement IDisposable in components in a way that makes sense for subclasses and scripts
- [ ] tweak 2d shadows bias and dist
- [ ] optimize pixel snapping - cache quads when position didn't change, don't snap again
- [ ] provide optional input accumulators to use with systems ticking async or slower
- [ ] decent general-purpose prefab editor
- [ ] make a system for subsystems - don't simply use components static members
- [ ] find a decent yet performant alternative to blurring shadows - current one sucks
- [ ] use bitwise for ManagedChunkedComponent spatial optimization? drawback - POT
- [ ] provide more collider types - at very least polygon
- [ ] revamp Misc.cs
- [ ] revamp Serialization.cs
- [ ] review EntityContainer.cs

**Comment by Alan-FGR** [comment]
NOTE: Can't remember why I should implement IDisposable for components, doesn't seem necessary at all, noting here so I have a clue when that comes back to bite me in the ass :trollface:
