### ISSUE TITLE
Rewrite TODO

### ISSUE THREAD

**Issue by Alan-FGR** [Alan-FGR/aelum#20]
## Core
- [ ] Engine (prev Core)
- [ ] Scene
- [ ] Node (prev Entity)
- [ ] Plugin (prev Component)

## Generic Stuff
- [ ] Plugin System (prev ManagedComponent)
- [ ] SpatialPluginSystem (prev ManagedChunkedComponent)
- [ ] Debug Helper (opt pass cam for drawing)
- [ ] Rand (prev Randy)
- [ ] NodeContainer (prev EntityContainer)
- [ ] Script
- [ ] Serialization

## Basic Game Systems
- [ ] Input
- [ ] Grid
- [ ] Systems environment OR static resetting

## Rendering systems
- [ ] Debug Drawing
- [ ] Camera
- [ ] Quads
- [ ] Lights
- [ ] Sprites

## Sound Systems
- [ ] SoundPlayerPlugin
- [ ] OneShotPool
- [ ] BGMPlayer (sound system static member or abs in static class?)

## Physics Systems
- [ ] PhysicsSystem (holds world, manages plugins)
- [ ] Physical Body (base)
- [ ] StaticBody
- [ ] Dynamic/DynKinematic Bodies
- [ ] Colliders list

## UI
- [ ] UISystem - has rt, accesses input and viewport/fb

**Comment by Alan-FGR** [comment]
I'm using this as checklist for the kiss_yagni rewrite
