### ISSUE TITLE
KISS YAGN rewrite/revamp checklist

### ISSUE THREAD

**Issue by Alan-FGR** [Alan-FGR/aelum#24]
## Core
- [ ] Core
- [ ] Scene
- [ ] Entity
- [ ] Component

## Generic Stuff
- [ ] ManagedComponent
- [ ] ManagedChunkedComponent
- [ ] Debug Helper (opt pass cam for drawing)
- [ ] Randy
- [ ] EntityContainer
- [ ] Script
- [ ] Serialization

## Basic Game Systems
- [ ] Input
- [ ] Grid
- [ ] Systems environment OR static resetting

## Rendering systems
- [ ] Debug Drawing
- [ ] Camera
- [ ] Quads
- [ ] Lights
- [ ] Sprites

## Sound Systems
- [ ] SoundPlayerPlugin
- [ ] OneShotPool
- [ ] BGMPlayer (sound system static member or abs in static class?)

## Physics Systems
- [ ] PhysicsSystem (holds world, manages plugins)
- [ ] Physical Body (base)
- [ ] StaticBody
- [ ] Dynamic/DynKinematic Bodies
- [ ] Colliders list

## UI
- [ ] UISystem - has rt, accesses input and viewport/fb
